services:
  - type: web
    name: confidentiality-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT chat_connect:app"
    plan: free
